# Generated by Django 5.2.13 on 2026-05-16 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('P', 'Presente (Temprano)'), ('T', 'Tarde'), ('J', 'Falta Justificada'), ('F', 'Falta')], default='F', max_length=1)),
                ('hora_registro', models.TimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.estudiante')),
            ],
            options={
                'verbose_name_plural': 'Asistencias de Estudiantes',
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Puntual'), ('T', 'Tardanza'), ('F', 'Falta'), ('J', 'Justificada')], default='F', max_length=1)),
                ('justificacion', models.TextField(blank=True, help_text='Motivo de la tardanza o falta', null=True)),
                ('tipo_actividad', models.CharField(choices=[('REGULAR', 'Clase/Jornada Regular'), ('ASESORIA', 'Asesoría/Reunión'), ('OTRO', 'Otro')], default='REGULAR', max_length=15)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personal.personal')),
            ],
            options={
                'verbose_name_plural': 'Asistencias del Personal',
                'unique_together': {('personal', 'fecha')},
            },
        ),
    ]
