# Generated by Django 5.2.13 on 2026-05-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Motivo de la falta o tardanza', null=True),
        ),
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('T', 'Tardanza'), ('F', 'Falta'), ('J', 'Falta Justificada')], default='P', max_length=1),
        ),
    ]
