# Generated by Django 5.2.13 on 2026-05-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_asistenciaestudiante_justificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones (Opcional)', null=True),
        ),
        migrations.AddField(
            model_name='asistenciapersonal',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones (Opcional)', null=True),
        ),
    ]
