# Generated by Django 5.2.13 on 2026-06-22 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_asistenciaestudiante_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('T', 'Tardanza'), ('F', 'Falta'), ('J', 'Falta Justificada')], db_index=True, default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistenciapersonal',
            name='estado',
            field=models.CharField(choices=[('P', 'Puntual'), ('T', 'Tardanza'), ('F', 'Falta'), ('J', 'Justificada')], db_index=True, default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistenciapersonal',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
    ]
