# Generated by Django 5.2.13 on 2026-08-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_asistenciaestudiante_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='bimestre',
            field=models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], db_index=True, default='I', max_length=3),
        ),
    ]
