# Generated by Django 5.2.13 on 2026-05-16 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(blank=True, help_text='Opcional', null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Curso Activo?')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('bimestre_actual', models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], default='I', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20)),
                ('grado', models.CharField(choices=[('3 Años', '3 Años'), ('4 Años', '4 Años'), ('5 Años', '5 Años'), ('1er Grado', '1er Grado'), ('2do Grado', '2do Grado'), ('3er Grado', '3er Grado'), ('4to Grado', '4to Grado'), ('5to Grado', '5to Grado'), ('6to Grado', '6to Grado'), ('1er Año', '1er Año'), ('2do Año', '2do Año'), ('3er Año', '3er Año'), ('4to Año', '4to Año'), ('5to Año', '5to Año')], max_length=50, verbose_name='Grado/Año')),
                ('seccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('denominacion', models.CharField(blank=True, help_text='Ej: Prototipo, Emprendedores', max_length=100, null=True)),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_tutoradas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'unique_together': {('grado', 'nivel', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(limit_choices_to={'cargo': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='personal.personal')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.periodolectivo')),
            ],
            options={
                'verbose_name': 'Asignación Académica',
                'verbose_name_plural': 'Asignaciones Académicas',
                'unique_together': {('curso', 'aula', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('telefono_apoderado', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del Apoderado')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Suspendido', 'Suspendido')], default='Activo', max_length=15)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.aula', verbose_name='Aula Actual')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESAFIO', 'Desafío Diario'), ('MENSUAL', 'Control de Calidad (Examen Mensual)'), ('BIMESTRAL', 'ISO Ingeniería (Examen Bimestral)'), ('SIMULACRO', 'Concurso de Aptitud (Simulacro)'), ('CUADERNO', 'Revisión de Cuaderno/Libros')], max_length=20)),
                ('bimestre', models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], default='I', max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.asignacionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo')),
            ],
            options={
                'unique_together': {('estudiante', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.CharField(default='I', max_length=5)),
                ('tema', models.CharField(choices=[('TEMA_1', 'Tema 1'), ('TEMA_2', 'Tema 2'), ('TEMA_3', 'Tema 3'), ('TEMA_4', 'Tema 4'), ('TEMA_5', 'Tema 5'), ('TEMA_6', 'Tema 6'), ('ASESORIA', 'Asesorías'), ('REPASO', 'Repaso / Adicional')], default='TEMA_1', max_length=20)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('LISTO', 'Listo para Recoger'), ('ENTREGADO', 'Entregado al Docente')], default='PENDIENTE', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignacionacademica')),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'DOC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Solicitud de Impresión',
                'verbose_name_plural': 'Solicitudes de Impresión',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SESION', 'Sesión de Aprendizaje'), ('FICHA', 'Ficha Aplicativa'), ('DESAFIO', 'Desafío Diario'), ('CALIDAD', 'Control de Calidad (Mensual)'), ('ISO', 'Examen ISO (Bimestral)'), ('ADICIONAL', 'Material Adicional')], max_length=20)),
                ('archivo', models.FileField(upload_to='materiales/%Y/%m/')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='academico.solicitudimpresion')),
            ],
            options={
                'verbose_name': 'Archivo de Material',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionActitudinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_evaluado', models.CharField(help_text='Ej: Marzo, Abril, Bimestre 1', max_length=20)),
                ('puntualidad', models.IntegerField(default=20)),
                ('presentacion', models.IntegerField(default=20)),
                ('cuidado_patrimonio', models.IntegerField(default=20)),
                ('orden_limpieza', models.IntegerField(default=20)),
                ('respeto_normas', models.IntegerField(default=20)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actitudinales', to='academico.matricula')),
            ],
            options={
                'verbose_name': 'Evaluación Actitudinal',
                'verbose_name_plural': 'Evaluaciones Actitudinales',
                'unique_together': {('matricula', 'mes_evaluado')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.evaluacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.matricula')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('matricula', 'evaluacion')},
            },
        ),
    ]
