# Generated by Django 5.2.13 on 2026-05-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionacademica',
            old_name='docente',
            new_name='personal',
        ),
        migrations.RenameField(
            model_name='solicitudimpresion',
            old_name='docente',
            new_name='personal',
        ),
    ]
