# Generated by Django 5.2.13 on 2026-05-22 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_rename_docente_asignacionacademica_personal_and_more'),
        ('personal', '0002_personal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Fotos del Periódico Mural de Marzo, Registro Auxiliar Semanal', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_evidencia', models.FileField(help_text='Sube la evidencia (PDF, Imagen, etc.)', upload_to='evidencias_docentes/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado / Requiere Corrección')], default='PENDIENTE', max_length=15)),
                ('observaciones_coordinacion', models.TextField(blank=True, help_text='Feedback para el docente en caso de correcciones.', null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_enviadas', to='personal.personal')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_revisadas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Evidencia de Docente',
                'verbose_name_plural': 'Evidencias de Docentes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones breves sobre este material.', null=True)),
                ('categoria', models.CharField(choices=[('FORMATO', 'Formatos y Plantillas'), ('AULA', 'Ambientación de Aula (Fotos Modelo)'), ('EVALUACION', 'Modelos de Evaluación'), ('GUIA', 'Guías y Manuales')], default='FORMATO', max_length=20)),
                ('archivo', models.FileField(help_text='Sube un PDF, Word, Excel o Imagen.', upload_to='materiales_coordinacion/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_publicados', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Material Institucional',
                'verbose_name_plural': 'Materiales Institucionales',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
