# Generated by Django 5.2.13 on 2026-05-22 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_evidenciadocente_materialinstitucional'),
        ('personal', '0002_personal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Detalles o Instrucciones')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('LIMITE', '⏰ Fecha Límite / Entrega'), ('REUNION', '👥 Reunión de Trabajo'), ('EFEMERIDE', '🎉 Evento / Efeméride'), ('URGENTE', '🚨 Alerta Institucional')], default='LIMITE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aula_afectada', models.ForeignKey(blank=True, help_text='Opcional: Si el evento aplica solo a un salón.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.aula')),
                ('creado_por', models.ForeignKey(limit_choices_to={'cargo__in': ['COO', 'DIR']}, on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Evento de Cronograma',
                'verbose_name_plural': 'Eventos del Cronograma',
                'ordering': ['fecha', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.periodolectivo')),
                ('personal', models.ForeignKey(limit_choices_to={'cargo': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='personal.personal', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
