# Generated by Django 5.2.13 on 2026-05-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_eventocronograma_horarioclase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocronograma',
            options={'ordering': ['fecha_inicio', 'fecha_creacion'], 'verbose_name': 'Evento de Cronograma', 'verbose_name_plural': 'Eventos del Cronograma'},
        ),
        migrations.RemoveField(
            model_name='eventocronograma',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='eventocronograma',
            name='tipo',
        ),
        migrations.AddField(
            model_name='eventocronograma',
            name='color',
            field=models.CharField(default='#e91e63', max_length=7, verbose_name='Color de Etiqueta'),
        ),
        migrations.AddField(
            model_name='eventocronograma',
            name='fecha_fin',
            field=models.DateField(default='2026-05-24', verbose_name='Fecha de Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventocronograma',
            name='fecha_inicio',
            field=models.DateField(default='2026-05-24', verbose_name='Fecha de Inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventocronograma',
            name='aula_afectada',
            field=models.ForeignKey(blank=True, help_text='Opcional: Si aplica solo a un salón.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.aula'),
        ),
    ]
