# Generated by Django 5.2.13 on 2026-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_eventocronograma_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocronograma',
            options={'ordering': ['fecha_inicio', 'hora_inicio', 'fecha_creacion'], 'verbose_name': 'Evento de Cronograma', 'verbose_name_plural': 'Eventos del Cronograma'},
        ),
        migrations.AddField(
            model_name='eventocronograma',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='eventocronograma',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
