# Generated by Django 5.2.13 on 2026-05-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_eventocronograma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioclase',
            name='color',
            field=models.CharField(default='#17c1e8', max_length=7, verbose_name='Color de Bloque'),
        ),
    ]
