# Generated by Django 5.2.13 on 2026-05-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_horarioclase_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRecreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=15, unique=True, verbose_name='Nivel Escolar')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('nombre', models.CharField(default='RECREO', max_length=50, verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Horario de Recreo',
                'verbose_name_plural': 'Horarios de Recreo',
            },
        ),
    ]
