# Generated by Django 5.2.13 on 2026-05-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_horariorecreo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodolectivo',
            options={'ordering': ['-anio'], 'verbose_name': 'Periodo Lectivo', 'verbose_name_plural': 'Periodos Lectivos'},
        ),
        migrations.RemoveField(
            model_name='periodolectivo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='periodolectivo',
            name='anio',
            field=models.PositiveIntegerField(default=2026, unique=True, verbose_name='Año Escolar'),
            preserve_default=False,
        ),
    ]
