# Generated by Django 5.2.13 on 2026-05-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_alter_periodolectivo_options_and_more'),
        ('personal', '0002_personal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Material')),
                ('categoria', models.CharField(choices=[('MOBILIARIO', 'Mobiliario (Mesas, Sillas, Pizarras)'), ('DIDACTICO', 'Material Didáctico (Mapas, Libros, Juegos)'), ('TECNOLOGICO', 'Equipos Tecnológicos (Proyectores, PCs)'), ('OTROS', 'Otros / Varios')], default='MOBILIARIO', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si el colegio ya no usa este tipo de material')),
            ],
            options={
                'verbose_name': 'Catálogo de Material',
                'verbose_name_plural': 'Catálogo de Materiales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buen_estado', models.PositiveIntegerField(default=0, verbose_name='Buen Estado')),
                ('regular', models.PositiveIntegerField(default=0, verbose_name='Regular')),
                ('mal_estado', models.PositiveIntegerField(default=0, verbose_name='Mal Estado')),
                ('se_requiere', models.PositiveIntegerField(default=0, verbose_name='Se Requiere (Faltantes)')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='academico.aula')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_aula', to='academico.catalogomaterial')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='academico.periodolectivo')),
            ],
            options={
                'verbose_name': 'Inventario de Aula',
                'verbose_name_plural': 'Inventarios de Aulas',
                'unique_together': {('periodo', 'aula', 'material')},
            },
        ),
    ]
