# Generated by Django 5.2.13 on 2026-05-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_catalogomaterial_inventarioaula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogomaterial',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo de Material', 'verbose_name_plural': 'Catálogo de Materiales'},
        ),
        migrations.RemoveField(
            model_name='catalogomaterial',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='catalogomaterial',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar si ya no se usa'),
        ),
    ]
