# Generated by Django 5.2.13 on 2026-05-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_catalogomaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='1-spwXHtIp9SHs28wnL-ZZ7oqUBTyt8Gf', max_length=150, null=True),
        ),
    ]
