# Generated by Django 5.2.13 on 2026-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_aula_google_sheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='1MQlfPcVd3b_jcGjsLcYoRzXVn30ZhUvenDqNptU-loM', max_length=150, null=True),
        ),
    ]
