# Generated by Django 5.2.13 on 2026-06-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_alter_aula_google_sheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='Pegue aquí el ID del Excel de Google Drive', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('DESAFIO', 'Desafío Diario'), ('MENSUAL', 'Control de Calidad (Examen Mensual)'), ('BIMESTRAL', 'ISO Ingeniería (Examen Bimestral)'), ('SIMULACRO', 'Concurso de Aptitud (Simulacro)'), ('CUADERNO', 'Revisión de Cuaderno'), ('LIBRO', 'Revisión de Libro')], max_length=20),
        ),
    ]
