# Generated by Django 5.2.13 on 2026-06-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_aula_google_sheet_id_alter_evaluacion_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionactitudinal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evaluacionactitudinal',
            name='bimestre',
            field=models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], default='I', max_length=5, verbose_name='Bimestre Evaluado'),
        ),
        migrations.RemoveField(
            model_name='evaluacionactitudinal',
            name='mes_evaluado',
        ),
    ]
