# Generated by Django 5.2.13 on 2026-06-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_alter_evaluacionactitudinal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionactitudinal',
            unique_together={('matricula', 'bimestre')},
        ),
    ]
