# Generated by Django 5.2.13 on 2026-06-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_alter_evaluacionactitudinal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionactitudinal',
            name='recomendacion_ia',
            field=models.TextField(blank=True, help_text='Almacena las 4 recomendaciones generadas por Gemini en formato JSON.', null=True),
        ),
    ]
