# Generated by Django 5.2.13 on 2026-06-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_evaluacionactitudinal_recomendacion_ia'),
        ('personal', '0002_personal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: II CONCURSO DE APTITUD ACADÉMICA', max_length=100)),
                ('mes', models.CharField(help_text='Ej: Abril, Mayo', max_length=50)),
                ('grado', models.CharField(max_length=50, verbose_name='Grado/Año')),
                ('nivel', models.CharField(choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20)),
                ('fecha_examen', models.DateField()),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, los profesores pueden enviar preguntas')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo')),
            ],
            options={
                'verbose_name': 'Simulacro',
                'verbose_name_plural': 'Simulacros',
            },
        ),
        migrations.CreateModel(
            name='PreguntaSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(help_text='Texto principal de la pregunta')),
                ('imagen', models.ImageField(blank=True, help_text='Opcional. Sube la imagen del gráfico o fórmula.', null=True, upload_to='simulacros/imagenes/')),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(max_length=255)),
                ('opcion_d', models.CharField(max_length=255)),
                ('opcion_e', models.CharField(default='N.A.', max_length=255)),
                ('respuesta_correcta', models.CharField(choices=[('a', 'Opción A'), ('b', 'Opción B'), ('c', 'Opción C'), ('d', 'Opción D'), ('e', 'Opción E')], max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_simulacro', to='personal.personal')),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academico.simulacro')),
            ],
            options={
                'verbose_name': 'Pregunta de Simulacro',
                'verbose_name_plural': 'Preguntas de Simulacro',
                'ordering': ['curso__nombre', 'id'],
            },
        ),
    ]
