# Generated by Django 5.2.13 on 2026-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_simulacro_preguntasimulacro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['area', 'nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='area',
            field=models.CharField(choices=[('APTITUD', 'Aptitud Académica'), ('MATEMATICA', 'Matemática'), ('CIENCIAS', 'Ciencias'), ('LETRAS', 'Letras'), ('TALLERES', 'Talleres')], default='LETRAS', max_length=20, verbose_name='Área Académica'),
        ),
    ]
