# Generated by Django 5.2.13 on 2026-06-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_alter_curso_options_curso_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasimulacro',
            name='opcion_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasimulacro',
            name='opcion_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preguntasimulacro',
            name='opcion_e',
            field=models.CharField(blank=True, default='N.A.', max_length=255, null=True),
        ),
    ]
