# Generated by Django 5.2.13 on 2026-06-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_alter_preguntasimulacro_opcion_c_and_more'),
        ('personal', '0002_personal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False, verbose_name='¿Envío Terminado?')),
                ('fecha_entrega', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_control', to='academico.simulacro')),
            ],
            options={
                'unique_together': {('simulacro', 'curso', 'docente')},
            },
        ),
    ]
