# Generated by Django 5.2.13 on 2026-06-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_entregasimulacro'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='preguntas_esperadas',
            field=models.PositiveIntegerField(default=100, help_text='Ej: 40 para Inicial, 100 para Primaria, 120 para Secundaria'),
        ),
    ]
