# Generated by Django 5.2.13 on 2026-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_alter_curso_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Consorcio Educativo Ingeniería', max_length=100)),
                ('sede', models.CharField(default='Sede Principal', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número para WhatsApp (+51...)', max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo_modular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Modular')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('director', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Director(a)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institucion/')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Configuración de la Institución',
            },
        ),
    ]
