# Generated by Django 5.2.13 on 2026-06-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0024_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodolectivo',
            name='pausar_notificaciones',
            field=models.BooleanField(default=False, verbose_name='Pausar alertas automáticas (Feriados/Vacaciones)'),
        ),
    ]
