# Generated by Django 5.2.13 on 2026-06-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0025_periodolectivo_pausar_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='¿Curso Activo?'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.CharField(choices=[('MATEMATICA', 'Matemática'), ('COMUNICACION', 'Comunicación'), ('PERSONAL SOCIAL', 'Personal Social'), ('CIENCIA Y TECNOLOGIA', 'Ciencia y Tecnología'), ('CIENCIAS SOCIALES', 'Ciencias Sociales'), ('DPCC - ORATORIA', 'Desarrollo Personal, Ciudadanía y Cívica - Oratoria'), ('ARTE, CULTURA Y DANZA', 'Arte, Cultura y Danza'), ('EDUCACION PARA EL TRABAJO - COMPUTACION', 'Educación para el Trabajo - Computación'), ('EDUCACION RELIGIOSA - PSICOLOGIA', 'Educación Religiosa - Psicología'), ('PSICOMOTRICIDAD', 'Psicomotriz (Ed. Fisica)'), ('ARTE', 'Arte y Cultura'), ('RELIGION', 'Religión'), ('EDUCACION FISICA', 'Educación Física'), ('TALLERES', 'Talleres')], db_index=True, default='COMUNICACION', max_length=60, verbose_name='Área Académica'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Suspendido', 'Suspendido')], db_index=True, default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='bimestre',
            field=models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], db_index=True, default='I', max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('DESAFIO', 'Desafío Diario'), ('MENSUAL', 'Control de Calidad (Examen Mensual)'), ('BIMESTRAL', 'ISO Ingeniería (Examen Bimestral)'), ('SIMULACRO', 'Concurso de Aptitud (Simulacro)'), ('CUADERNO', 'Revisión de Cuaderno'), ('LIBRO', 'Revisión de Libro')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluacionactitudinal',
            name='bimestre',
            field=models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], db_index=True, default='I', max_length=5, verbose_name='Bimestre Evaluado'),
        ),
        migrations.AlterField(
            model_name='eventocronograma',
            name='fecha_fin',
            field=models.DateField(db_index=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='eventocronograma',
            name='fecha_inicio',
            field=models.DateField(db_index=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='evidenciadocente',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado / Requiere Corrección')], db_index=True, default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='evidenciadocente',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='dia_semana',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='hora_fin',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='hora_inicio',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='solicitudimpresion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('LISTO', 'Listo para Recoger'), ('ENTREGADO', 'Entregado al Docente')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudimpresion',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
