# Generated by Django 5.2.13 on 2026-07-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0026_alter_curso_activo_alter_curso_area_and_more'),
        ('personal', '0003_alter_personal_apellidos_alter_personal_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioclase',
            name='personal',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='personal.personal', verbose_name='Docente'),
        ),
    ]
