# Generated by Django 5.2.13 on 2026-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0027_alter_horarioclase_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocronograma',
            name='tipo_academico',
            field=models.CharField(choices=[('NINGUNO', '📌 Evento Regular / Sin alerta'), ('TEMA_1', '📘 Tema 1'), ('TEMA_2', '📘 Tema 2'), ('TEMA_3', '📘 Tema 3'), ('TEMA_4', '📘 Tema 4'), ('TEMA_5', '📘 Tema 5'), ('TEMA_6', '📘 Tema 6'), ('CALIDAD', '📝 Examen: Control de Calidad'), ('ISO', '🎓 Examen: ISO Ingeniería'), ('SIMULACRO', '🏆 Concurso de Aptitud (Simulacro)')], db_index=True, default='NINGUNO', max_length=20, verbose_name='Hito Académico'),
        ),
    ]
