# Generated by Django 5.2.13 on 2026-07-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0028_eventocronograma_tipo_academico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreRegistroBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.CharField(choices=[('I', 'Bimestre I'), ('II', 'Bimestre II'), ('III', 'Bimestre III'), ('IV', 'Bimestre IV')], max_length=5)),
                ('cerrado', models.BooleanField(default=False, verbose_name='¿Registro Cerrado?')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='academico.asignacionacademica')),
            ],
            options={
                'verbose_name': 'Cierre de Registro',
                'verbose_name_plural': 'Cierres de Registros',
                'unique_together': {('asignacion', 'bimestre')},
            },
        ),
    ]
