# Generated by Django 5.2.13 on 2026-07-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0029_cierreregistrobimestral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='aula',
        ),
    ]
