# Generated by Django 5.2.13 on 2026-08-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0030_remove_estudiante_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PTP', 'PTP / CPP'), ('PAS', 'Pasaporte'), ('INT', 'Código Interno (Sin Documento)')], default='DNI', max_length=3, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número de Documento'),
        ),
    ]
