# Generated by Django 5.2.13 on 2026-08-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0031_estudiante_tipo_documento_alter_estudiante_dni'),
        ('personal', '0005_alter_personal_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionacademica',
            name='personal',
            field=models.ForeignKey(limit_choices_to={'cargo__in': ['DOC', 'DIR']}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='personal.personal'),
        ),
    ]
