# Generated by Django 5.2.13 on 2026-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0032_alter_asignacionacademica_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel_exclusivo',
            field=models.CharField(choices=[('INI', 'Inicial'), ('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('GEN', 'General')], default='GEN', max_length=15, verbose_name='Nivel Exclusivo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'nivel_exclusivo')},
        ),
    ]
