# Generated by Django 5.2.13 on 2026-09-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0034_alter_curso_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.CharField(choices=[('MATEMATICA', 'Matemática'), ('COMUNICACION', 'Comunicación'), ('PERSONAL SOCIAL', 'Personal Social'), ('CIENCIA Y TECNOLOGIA', 'Ciencia y Tecnología'), ('CIENCIAS SOCIALES', 'Ciencias Sociales'), ('DPCC - ORATORIA', 'Desarrollo Personal, Ciudadanía y Cívica - Oratoria'), ('ARTE, CULTURA Y DANZA', 'Arte, Cultura y Danza'), ('EDUCACION PARA EL TRABAJO - COMPUTACION', 'Educación para el Trabajo - Computación'), ('EDUCACION RELIGIOSA - PSICOLOGIA', 'Educación Religiosa - Psicología'), ('PSICOMOTRICIDAD', 'Psicomotriz (Ed. Física)'), ('ARTE', 'Arte y Cultura'), ('RELIGION', 'Religión'), ('INGLES', 'Inglés'), ('EDUCACION FISICA', 'Educación Física'), ('TALLERES', 'Talleres')], db_index=True, default='COMUNICACION', max_length=60, verbose_name='Área Académica'),
        ),
    ]
