# Generated by Django 5.2.13 on 2026-09-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0035_alter_curso_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionacademica',
            options={'ordering': ['curso__nombre'], 'verbose_name': 'Asignación Académica', 'verbose_name_plural': 'Asignaciones Académicas'},
        ),
    ]
