# Generated by Django 5.2.13 on 2026-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0037_historicalnota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioclase',
            name='color',
            field=models.CharField(default='#f57905', max_length=7, verbose_name='Color de Bloque'),
        ),
    ]
