# Generated by Django 5.2.13 on 2026-06-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0026_alter_curso_activo_alter_curso_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('LIBRETA_AULA', 'Libretas de Aula (Excel)'), ('MATRIZ_CURSO', 'Matriz Oficial de Curso (Excel)'), ('AGENDA_TICKETS', 'Tickets de Agenda Semanal (Excel)'), ('DIAGNOSTICO_IA', 'Diagnóstico General IA (PDF)')], db_index=True, max_length=50)),
                ('archivo_generado', models.FileField(upload_to='reportes_generados/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tiempo_procesamiento_segundos', models.FloatField(default=0.0)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.aula')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.periodolectivo')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
