# Generated by Django 5.2.13 on 2026-05-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Actividad/Entregable')),
                ('descripcion', models.TextField(verbose_name='Instrucciones')),
                ('formato_adjunto', models.FileField(blank=True, help_text='Ej: Plantilla en Word o PDF a llenar', null=True, upload_to='formatos_actividades/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha Límite de Entrega')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad / Entregable',
                'verbose_name_plural': 'Actividades y Entregables',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Comunicado')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('importancia', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='comunicados/', verbose_name='Archivo Adjunto (Opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha en la que dejará de aparecer en el modal', null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado Oficial',
                'verbose_name_plural': 'Comunicados Oficiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='evidencias_personal/')),
                ('comentario_personal', models.TextField(blank=True, help_text='Nota opcional al entregar', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('REVISADO', 'Revisado por Coordinación')], default='PENDIENTE', max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='comunicaciones.actividad')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_subidas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Evidencia de Personal',
                'verbose_name_plural': 'Evidencias del Personal',
                'unique_together': {('actividad', 'personal')},
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='comunicaciones.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_leidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Lectura',
                'verbose_name_plural': 'Controles de Lectura',
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
