# Generated by Django 5.2.13 on 2026-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Sigue Activo?'),
        ),
    ]
