# Generated by Django 5.2.13 on 2026-06-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0003_comunicado_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha_limite',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha Límite de Entrega'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='¿Sigue Activo?'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha en la que dejará de aparecer en el modal', null=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='importancia',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidenciaactividad',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('REVISADO', 'Revisado por Coordinación')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidenciaactividad',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lecturacomunicado',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
