# Generated by Django 5.2.13 on 2026-07-02 23:07

import apps.comunicaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0004_alter_actividad_fecha_limite_alter_comunicado_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='comunicados/', validators=[apps.comunicaciones.models.validar_peso_archivo], verbose_name='Archivo Adjunto (Opcional)'),
        ),
        migrations.AlterField(
            model_name='evidenciaactividad',
            name='archivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_personal/', validators=[apps.comunicaciones.models.validar_peso_archivo]),
        ),
    ]
