# Generated by Django 5.2.13 on 2026-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0005_alter_comunicado_archivo_adjunto_and_more'),
        ('personal', '0003_alter_personal_apellidos_alter_personal_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='audiencia',
            field=models.CharField(choices=[('TODOS', 'Todo el Personal (General)'), ('DOCENTES', 'Todos los Docentes (Fijos / Por horas)'), ('TUTORES', 'Solo Tutores de Aula'), ('HORAS', 'Docentes Secundaria / Por horas'), ('ADMINISTRATIVOS', 'Solo Administrativos (Dir, Coo, Sec, Asi)'), ('INICIAL', 'Tutores Inicial'), ('PRIMARIA', 'Tutores Primaria'), ('SECUNDARIA', 'Tutores Secundaria'), ('PERSONALIZADO', 'Personalizado (Selección Manual)')], db_index=True, default='TODOS', max_length=20),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='destinatarios_especificos',
            field=models.ManyToManyField(blank=True, related_name='comunicados_especificos', to='personal.personal'),
        ),
    ]
