# Generated by Django 5.2.13 on 2026-07-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0006_comunicado_audiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='audiencia',
            field=models.CharField(choices=[('TODOS', 'Todo el Personal (General)'), ('DOCENTES', 'Todos los Docentes'), ('ADMINISTRATIVOS', 'Personal Administrativo'), ('PERSONALIZADO', 'Personalizado (Filtros Avanzados)...')], db_index=True, default='TODOS', max_length=20),
        ),
    ]
