# Generated by Django 5.2.13 on 2026-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.CharField(choices=[('DIR', 'Director(a)'), ('COO', 'Coordinador(a)'), ('DOC', 'Docente'), ('SEC', 'Secretaria(o)'), ('ASI', 'Asistente'), ('AUX', 'Auxiliar'), ('LIM', 'Personal de Limpieza')], default='DOC', max_length=3, verbose_name='Cargo')),
                ('tipo_contrato', models.CharField(choices=[('Fijo', 'Fijo (Tiempo Completo)'), ('Por Horas', 'Por Horas (Secundaria/Talleres)')], max_length=20, verbose_name='Tipo de Contrato')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal del Colegio',
                'ordering': ['cargo', 'apellidos', 'nombres'],
            },
        ),
    ]
