# Generated by Django 5.2.13 on 2026-06-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('DIR', 'Director(a)'), ('COO', 'Coordinador(a)'), ('DOC', 'Docente'), ('SEC', 'Secretaria(o)'), ('ASI', 'Asistente'), ('AUX', 'Auxiliar'), ('LIM', 'Personal de Limpieza')], db_index=True, default='DOC', max_length=3, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_index=True, default='Activo', max_length=20),
        ),
    ]
