# Generated by Django 5.2.13 on 2026-08-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_tipo_documento_alter_personal_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('DIR', 'Director(a)'), ('COO', 'Coordinador(a)'), ('DOC', 'Docente'), ('SEC', 'Secretaria(o)'), ('ASI', 'Asistente'), ('AUX', 'Auxiliar'), ('MAN', 'Mantenimiento')], db_index=True, default='DOC', max_length=3, verbose_name='Cargo'),
        ),
    ]
